### ISSUE TITLE
Remove the other powerup when adding a new powerup

### ISSUE THREAD

**Issue by bjsi** [browneyedsoul/RemNote-Aligner#3]
If a user adds the `center` powerup, maybe you should remove the `right` powerup?

Similarly, if a user adds the `right` powerup, maybe you should remove the `center` powerup?

You can use this code:

```ts
rem.removePowerup(...)
````

And you might need to update permissions to `ReadCreateModifyDelete` in the manifest.json file.

**Comment by browneyedsoul** [comment]
That's a good point! I didn't thought about the after tag mixing situation UX workflow! Please wait ;)
